"use strict";
let backend=null;
const $=id=>document.getElementById(id);
const all=s=>[...document.querySelectorAll(s)];
const state={boot:null,source:"firefox",live:false,draining:false,file:false,liveText:"",fileText:""};
const views={live:["TRASCRIZIONE LIVE","Ascolto e trascrizione","Cattura Firefox o microfono e trascrive in tempo reale."],file:["TRASCRIZIONE FILE","Media locale","Trascrive progressivamente file audio e video senza bloccare l'interfaccia."],settings:["CONFIGURAZIONE","Impostazioni","Parametri persistenti validati dal backend Python."],logs:["DIAGNOSTICA","Log e dispositivi","Stato tecnico, log runtime e diagnostica audio del backend."]};
function call(name,args=[],cb=null){if(!backend||typeof backend[name]!=="function")return;if(cb)backend[name](...args,cb);else backend[name](...args)}
function json(v){try{return JSON.parse(v)}catch{return v}}
function notice(text,error=false){$("notice-text").textContent=text;$("notice").hidden=false;$("notice").classList.toggle("error",error)}
function switchView(name){all(".nav").forEach(b=>{const on=b.dataset.view===name;b.classList.toggle("active",on);if(on)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current")});all(".view").forEach(p=>{const on=p.dataset.panel===name;p.hidden=!on;p.classList.toggle("active",on)});const v=views[name];$("eyebrow").textContent=v[0];$("title").textContent=v[1];$("subtitle").textContent=v[2]}
function setOrb(id,on){$(id).classList.toggle("active",!!on)}
function globalStatus(text,on=false){$("global-status").textContent=text;setOrb("global-orb",on)}
function progress(kind,value){const n=Math.max(0,Math.min(100,Number(value)||0));$(kind+"-fill").style.width=n+"%";$(kind+"-progress").setAttribute("aria-valuenow",String(n));$(kind==="buffer"?"buffer-value":"file-progress-value").textContent=Math.round(n)+"%"}
function text(kind,value,full=false){const box=$(kind+"-transcript");if(full)state[kind+"Text"]=String(value||"");else state[kind+"Text"]+=(state[kind+"Text"]?" ":"")+String(value||"");box.textContent=state[kind+"Text"]||"Il testo trascritto apparirà qui.";box.classList.toggle("placeholder",!state[kind+"Text"]);box.scrollTop=box.scrollHeight}
function liveUI(status){$("live-status").textContent=status;$("live-label").textContent=status;const busy=state.live||state.draining;$("live-start").disabled=busy||state.file;$("live-stop").disabled=!busy;$("live-drain").disabled=!state.live||state.draining;setOrb("live-orb",busy);lockSettings()}
function fileUI(status){$("file-status").textContent=status;$("file-label").textContent=status;$("file-start").disabled=state.file||state.live||state.draining;$("file-stop").disabled=!state.file;setOrb("file-orb",state.file);lockSettings()}
function lockSettings(){$("settings-save").disabled=state.live||state.draining||state.file}
function options(select,values,current){select.innerHTML="";values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;o.selected=v===current;select.append(o)})}
function devices(source,list){const s=$("live-device"),current=s.value;s.innerHTML='<option value="">Rilevamento automatico</option>';const key=source==="firefox"?"is_monitor":"is_mic";(list||[]).filter(d=>d[key]).forEach(d=>{const o=document.createElement("option");o.value=d.name;o.textContent=d.name+(d.hostapi_name?" · "+d.hostapi_name:"");s.append(o)});if([...s.options].some(o=>o.value===current))s.value=current}
function hydrate(b){state.boot=b;$("version").textContent="v"+b.app.version;options($("live-model"),b.modelChoices,b.settings.model_size);options($("file-model"),b.modelChoices,b.settings.model_size);options($("s-model"),b.modelChoices,b.settings.model_size);$("live-language").value=b.settings.language;$("file-language").value=b.settings.language;state.source=b.settings.audio_source;sourceUI();devices(state.source,b.devices);$("live-model-value").textContent=b.settings.model_size;const map={"s-language":"language","s-source":"audio_source","s-beam":"beam_size","s-vad-silence":"vad_min_silence_ms","s-buffer":"buffer_warn_threshold","s-chunk":"chunk_ms","s-channels":"channels","s-sink":"sink_name","s-keyword":"sink_search_keyword","s-port":"server_port","s-gpu":"gpu_layers","s-compute":"compute_type","s-width":"window_width","s-height":"window_height"};for(const [id,key] of Object.entries(map))$(id).value=b.settings[key]??"";$("s-vad").checked=!!b.settings.vad_filter;state.live=!!b.runtime.liveRunning;state.draining=!!b.runtime.liveDraining;state.file=!!b.runtime.fileRunning;progress("buffer",b.runtime.bufferLevel);liveUI(state.draining?"Completamento buffer":state.live?"In esecuzione":"Idle");fileUI(state.file?"In esecuzione":"Idle");globalStatus(b.runtime.backendRunning?"Pronto":"Standby",b.runtime.backendRunning);$("log-output").textContent=b.logTail||"Nessun log persistente disponibile."}
function sourceUI(){all(".segment").forEach(b=>{const on=b.dataset.source===state.source;b.classList.toggle("active",on);b.setAttribute("aria-pressed",String(on))});$("live-source-value").textContent=state.source==="firefox"?"Firefox":"Microfono"}
function refreshDevices(){call("refreshDevices",[state.source],r=>devices(state.source,json(r)))}
function appendLog(level,name,message){const out=$("log-output");if(out.textContent.startsWith("In attesa")||out.textContent.startsWith("Nessun log"))out.textContent="";out.textContent+=`[${level}] ${name}: ${message}\n`;if($("log-auto").checked)out.scrollTop=out.scrollHeight}
function event(name,payload){const p=json(payload);switch(name){case"backend_status_changed":globalStatus(String(p||"Backend"),String(p).toLowerCase().includes("ready")||String(p).toLowerCase().includes("running"));break;case"process_started":state.live=true;state.draining=false;globalStatus("Trascrizione live",true);liveUI("In esecuzione");break;case"capture_stopped":state.live=false;state.draining=true;liveUI("Completamento buffer");break;case"process_stopped":state.live=false;state.draining=false;progress("buffer",0);liveUI("Fermata");globalStatus("Pronto",true);break;case"transcriber_drained":state.live=false;state.draining=false;progress("buffer",0);liveUI("Completata");globalStatus("Pronto",true);break;case"transcriber_status_changed":liveUI(label(p));break;case"transcriber_buffer_level":progress("buffer",p);break;case"transcriber_new_text":text("live",p);break;case"transcriber_error":state.live=false;state.draining=false;liveUI("Errore");notice(String(p),true);break;case"file_transcriber_status_changed":state.file=!['completed','stopped','error'].includes(String(p));fileUI(label(p));if(state.file)globalStatus("Trascrizione file",true);break;case"file_transcriber_progress":progress("file",p);break;case"file_transcriber_new_text":text("file",p);break;case"file_transcriber_full_text":text("file",p,true);break;case"file_transcriber_completed":state.file=false;fileUI("Completata");progress("file",100);globalStatus("Pronto",true);break;case"file_transcriber_error":state.file=false;fileUI("Errore");notice(String(p),true);break;case"config_changed":if(state.boot&&p&&typeof p==="object")state.boot.settings={...state.boot.settings,...p};break;case"audio_diagnostics":$("diagnostics-output").textContent=String(p);break;case"audio_diagnostics_error":$("diagnostics-output").textContent=String(p);notice(String(p),true)}}
function label(v){return({idle:"Idle",running:"In esecuzione",buffering:"Buffering",error:"Errore",loading_model:"Caricamento modello",isolating_vocals:"Isolamento voce",stopped:"Fermata",completed:"Completata"})[String(v)]||String(v)}
async function copyValue(value){const t=String(value||"");try{await navigator.clipboard.writeText(t);notice("Copiato negli appunti")}catch{const a=document.createElement("textarea");a.value=t;document.body.append(a);a.select();document.execCommand("copy");a.remove();notice("Copiato negli appunti")}}
function startLive(){const model=$("live-model").value,go=()=>call("startLive",[state.source,$("live-device").value,$("live-language").value]);if(state.boot&&model!==state.boot.settings.model_size)call("applySettings",[JSON.stringify({model_size:model})],r=>{const x=json(r);if(x.ok){state.boot.settings=x.settings;go()}else notice(x.error,true)});else go()}
function startFile(){const path=$("file-path").value;if(!path){notice("Seleziona un file da trascrivere",true);return}call("startFile",[path,$("file-language").value,$("file-model").value,$("song-mode").checked,$("isolate-vocals").checked])}
function saveSettings(e){e.preventDefault();const f=e.currentTarget,p={};for(const el of f.elements){if(!el.name)continue;if(el.type==="checkbox")p[el.name]=el.checked;else if(el.type==="number")p[el.name]=Number(el.value);else p[el.name]=el.value===""&&el.name==="sink_name"?null:el.value}call("applySettings",[JSON.stringify(p)],r=>{const x=json(r);if(!x.ok){notice(x.error,true);return}state.boot.settings=x.settings;$("live-language").value=x.settings.language;$("file-language").value=x.settings.language;$("live-model").value=x.settings.model_size;$("file-model").value=x.settings.model_size;$("live-model-value").textContent=x.settings.model_size;notice("Impostazioni salvate")})}
function bind(){all(".nav").forEach(b=>b.onclick=()=>switchView(b.dataset.view));all(".segment").forEach(b=>b.onclick=()=>{state.source=b.dataset.source;sourceUI();refreshDevices()});all(".toggle-row input").forEach(input=>{const visual=input.nextElementSibling;if(!visual)return;input.addEventListener("focus",()=>{visual.style.boxShadow="var(--shadow-active)"});input.addEventListener("blur",()=>{visual.style.boxShadow=""})});$("notice-close").onclick=()=>$("notice").hidden=true;$("live-start").onclick=startLive;$("live-stop").onclick=()=>call("stopLive");$("live-drain").onclick=()=>call("stopListening");$("file-pick").onclick=()=>call("chooseAudioFile",[],p=>{if(p)$("file-path").value=p});$("file-start").onclick=startFile;$("file-stop").onclick=()=>call("stopFile");$("song-mode").onchange=e=>{$("isolate-vocals").disabled=!e.target.checked;if(!e.target.checked)$("isolate-vocals").checked=false};$("live-copy").onclick=()=>copyValue(state.liveText);$("file-copy").onclick=()=>copyValue(state.fileText);$("live-clear").onclick=()=>{state.liveText="";text("live","",true)};$("file-clear").onclick=()=>{state.fileText="";text("file","",true)};$("settings-form").onsubmit=saveSettings;$("log-refresh").onclick=()=>call("readLogTail",[300],r=>$("log-output").textContent=r||"Nessun log persistente disponibile.");$("log-copy").onclick=()=>copyValue($("log-output").textContent);$("diagnostics-run").onclick=()=>{$("diagnostics-output").textContent="Diagnostica in corso…";call("runAudioDiagnostics")}}
function init(){bind();if(typeof QWebChannel==="undefined"){notice("Qt WebChannel non disponibile",true);return}new QWebChannel(qt.webChannelTransport,ch=>{backend=ch.objects.backend;backend.eventReceived.connect(event);backend.logReceived.connect(appendLog);call("getBootstrap",[],r=>hydrate(json(r)))})}
document.addEventListener("DOMContentLoaded",init);
